---
- name : Install de git et clone du repo
  hosts: all
  become: yes

  tasks:
    - name: Install de git
      yum:
        name: git
        state: present

    - name: Clone du repo
      git:
        repo: https://github.com/diranetafen/static-website-example
        dest: /data
