---
- name: Installation de docker
  hosts: all
  become: yes
  tasks:

    - name: Installation des dépendances de docker
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Ajout du repo docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644

    - name: Installation de docker-ce
      yum:
        name: docker-ce
        state: present

    - name: Start et enable du daemon docker
      service:
        name: docker
        state: started
        enabled: yes

